version: 2
updates:
  # Enable version updates for Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "speakeasy-api/maintainers"
    assignees:
      - "speakeasy-api/maintainers"
    commit-message:
      prefix: "deps"
      prefix-development: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "go"
    groups:
      # Group patch and minor updates together
      go-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      # Keep major updates separate for careful review
      go-major:
        patterns:
          - "*"
        update-types:
          - "major"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "speakeasy-api/maintainers"
    assignees:
      - "speakeasy-api/maintainers"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      github-actions:
        patterns:
          - "*"
