#!/usr/bin/env bash
set -euo pipefail

# Script to format Go coverage output as a markdown table
# Usage: ./format-coverage.sh coverage.out [current-coverage] [main-coverage] [main-status]

COVERAGE_FILE="${1:-coverage.out}"
CURRENT_COVERAGE="${2:-}"
MAIN_COVERAGE="${3:-}"
MAIN_STATUS="${4:-}"

if [ ! -f "$COVERAGE_FILE" ]; then
    echo "Error: Coverage file '$COVERAGE_FILE' not found"
    exit 1
fi

NORMALIZED_FILE=$(mktemp)
trap 'rm -f "$NORMALIZED_FILE"' EXIT
bash "$(dirname "$0")/normalize-coverage.sh" "$COVERAGE_FILE" > "$NORMALIZED_FILE"
COVERAGE_FILE="$NORMALIZED_FILE"

# Start markdown output
echo "## 📊 Test Coverage Report"
echo ""

# Show current and main coverage if provided
if [ -n "$CURRENT_COVERAGE" ]; then
    echo "**Current Statement Coverage:** \`$CURRENT_COVERAGE\`"
    
    if [ -n "$MAIN_COVERAGE" ]; then
        echo "**Main Branch Statement Coverage:** \`$MAIN_COVERAGE\`"
        echo ""
        
        # Calculate difference
        CURRENT_NUM=$(echo "$CURRENT_COVERAGE" | sed 's/%//')
        MAIN_NUM=$(echo "$MAIN_COVERAGE" | sed 's/%//')
        
        if [ -n "$CURRENT_NUM" ] && [ -n "$MAIN_NUM" ]; then
            DIFF=$(echo "$CURRENT_NUM - $MAIN_NUM" | bc -l 2>/dev/null || echo "0")
            
            if [ "$(echo "$DIFF > 0" | bc -l 2>/dev/null || echo "0")" = "1" ]; then
                echo "**Coverage Change:** 📈 +${DIFF}% (improved)"
            elif [ "$(echo "$DIFF < 0" | bc -l 2>/dev/null || echo "0")" = "1" ]; then
                DIFF_ABS=$(echo "$DIFF * -1" | bc -l 2>/dev/null || echo "${DIFF#-}")
                echo "**Coverage Change:** 📉 -${DIFF_ABS}% (decreased)"
            else
                echo "**Coverage Change:** ✅ No change"
            fi
        fi
    elif [ -n "$MAIN_STATUS" ]; then
        echo "**Main Branch Statement Coverage:** unavailable ($MAIN_STATUS). Comparison omitted."
    fi
fi

echo ""
echo "### Statement Coverage by Package"
echo ""
echo "Go measures covered statements. Codecov measures fully covered lines, so its percentage can differ."
echo ""

# Create table header
echo "| Package | Coverage |"
echo "|---------|----------|"

# Count statements, not averages of function percentages, from normalized blocks.
awk '
NR > 1 {
    pkg = $1;
    sub(/\/[^\/]+$/, "", pkg);
    totals[pkg] += $2;
    if($3 > 0) covered[pkg] += $2;
}
END {
    for(pkg in totals) {
        avg = (totals[pkg] > 0) ? 100 * covered[pkg] / totals[pkg] : 0;
        
        # Format package name (remove common prefix)
        display_pkg = pkg;
        gsub(/github\.com\/speakeasy-api\/openapi\//, "", display_pkg);
        
        # Add emoji indicators based on coverage level
        emoji = "🔴";
        if(avg >= 90) emoji = "🟢";
        else if(avg >= 75) emoji = "🟡";
        else if(avg >= 50) emoji = "🟠";
        
        # Output with coverage value for sorting
        printf "%.1f|`%s`|%s\n", avg, display_pkg, emoji;
    }
}' "$COVERAGE_FILE" | sort -n | awk -F'|' '{
    # Re-format after sorting by coverage
    printf "| %s | %s %.1f%% |\n", $2, $3, $1;
}'

echo ""
echo "<details>"
echo "<summary>📋 Detailed Coverage by Function (click to expand)</summary>"
echo ""
echo "\`\`\`"
go tool cover -func="$COVERAGE_FILE"
echo "\`\`\`"
echo "</details>"
echo ""
echo "- 🧪 All tests passed"
echo "- 📈 Full coverage report available in workflow artifacts"
echo ""
echo "_Generated by GitHub Actions_"